### ISSUE TITLE
[crash] Webstorm EAP: ClassNotFoundException: com.intellij.json.psi.JsonProperty

### ISSUE THREAD

**Issue by SCjona** [WarningImHack3r/npm-update-dependencies#126]
### What is the issue?

not working on latest Webstorm EAP version

### What are the steps to reproduce this issue?

install WebStorm 2024.3 EAP Build: #WS-243.12818.48 September 11, 2024 and open package.json

### What were you expecting to happen?

outdated packages highlighted as usual

### Paste any relevant logs, error output, etc.

```shell
com.intellij.diagnostic.PluginException: annotator: com.github.warningimhack3r.npmupdatedependencies.ui.annotation.DeprecationAnnotator@43d7be50 (class com.github.warningimhack3r.npmupdatedependencies.ui.annotation.DeprecationAnnotator) [Plugin: com.github.warningimhack3r.npmupdatedependencies]
Caused by: java.lang.NoClassDefFoundError: com/intellij/json/psi/JsonProperty
	at com.github.warningimhack3r.npmupdatedependencies.ui.helpers.AnnotatorsCommon.getInfo(AnnotatorsCommon.kt:12)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.DeprecationAnnotator.collectInformation(DeprecationAnnotator.kt:34)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.DeprecationAnnotator.collectInformation(DeprecationAnnotator.kt:25)
	... 26 more
Caused by: java.lang.ClassNotFoundException: com.intellij.json.psi.JsonProperty PluginClassLoader(plugin=PluginDescriptor(name=NPM Update Dependencies, id=com.github.warningimhack3r.npmupdatedependencies, descriptorPath=plugin.xml, path=~/.local

<TRIMMED STACKTRACE>
```

### What OS are you experiencing the problem on?

Linux

### Additional platform information

Build version: WebStorm 2024.3 EAP Build: #WS-243.12818.48 September 11, 2024
JRE: 21.0.4+8-b589.3, JetBrains s.r.o.
JVM: 21.0.4+8-b589.3, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Linux 6.6.50-2-lts (amd64)

=== Plugins ===
Custom plugins: [NPM Update Dependencies (3.0.1), i18n support (2.6.2)]
Disabled plugins:[Chinese (Simplified) Language Pack / 中文语言包 (243.12818.48), Full Line Code Completion (243.12818.48)]

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
Hi there, yes I got warned by the compatibility verifier, I’m on it!
