### ISSUE TITLE
HTML registry response when trying to get package lastModified

### ISSUE THREAD

**Issue by xmasuhai** [WarningImHack3r/npm-update-dependencies#153]
### What is the issue?

IDE Error

```
ExternalToolPass: 

com.intellij.diagnostic.PluginException: annotator: com.github.warningimhack3r.npmupdatedependencies.ui.annotation.DeprecationAnnotator@49b180d (class com.github.warningimhack3r.npmupdatedependencies.ui.annotation.DeprecationAnnotator) [Plugin: com.github.warningimhack3r.npmupdatedependencies]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.processError(ExternalToolPass.java:268)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:225)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$0(ExternalToolPass.java:170)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:283)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$2(ExternalToolPass.java:170)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$runUnderDisposeAwareIndicator$15(BackgroundTaskUtil.java:371)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:217)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:366)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:168)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:366)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:356)
	at com.intellij.util.ui.update.MergingUpdateQueue.doFlush(MergingUpdateQueue.java:313)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:295)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:262)
	at com.intellij.util.Alarm$Request.lambda$runSafely$0(Alarm.java:371)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:97)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:92)
	at com.intellij.util.Alarm$Request.lambda$runSafely$1(Alarm.java:369)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:255)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:368)
	at com.intellij.util.Alarm$Request.run(Alarm.java:356)
	at com.intellij.util.concurrency.Propagation.contextAwareCallable$lambda$2(propagation.kt:383)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:212)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 11: Expected EOF after parsing, but had H instead at path: $
JSON input: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML .....
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:580)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:578)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.expectEof(AbstractJsonLexer.kt:192)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:166)
	at kotlinx.serialization.json.Json.parseToJsonElement(Json.kt:195)
	at com.github.warningimhack3r.npmupdatedependencies.backend.engine.NPMJSClient.getBodyAsJSON(NPMJSClient.kt:98)
	at com.github.warningimhack3r.npmupdatedependencies.backend.engine.NPMJSClient.getPackageLastModified(NPMJSClient.kt:200)
	at com.github.warningimhack3r.npmupdatedependencies.backend.engine.checkers.PackageDeprecationChecker.getDeprecationStatus(PackageDeprecationChecker.kt:83)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.DeprecationAnnotator$doAnnotate$2.invokeSuspend(DeprecationAnnotator.kt:82)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.DeprecationAnnotator$doAnnotate$2.invoke(DeprecationAnnotator.kt)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.DeprecationAnnotator$doAnnotate$2.invoke(DeprecationAnnotator.kt)
	at com.github.warningimhack3r.npmupdatedependencies.backend.extensions.ExtensionsKt$parallelMap$1$1$1$1.invokeSuspend(Extensions.kt:35)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
	Suppressed: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 11: Expected EOF after parsing, but had H instead at path: $
JSON input: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML .....
		... 20 more

```

### What are the steps to reproduce this issue?

WebStorm 2024.2.3 Build #WS-242.23339.15, built on September 25, 2024
win11
[3.4.0](https://plugins.jetbrains.com/plugin/21105-npm-update-dependencies/versions/stable/618341)

### What were you expecting to happen?

no IDE error

### What OS are you experiencing the problem on?

Windows

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
Hi there! It seems like your nom registry is returning an invalid response. Are you using a custom one? Can you [send me your logs](https://github.com/WarningImHack3r/npm-update-dependencies/blob/main/.github/TROUBLESHOOTING.md#enable-and-extract-logs) please?

**Comment by WarningImHack3r** [comment]
I improved the handling of HTTP errors in 3338b36 as I assume this comes from some non-200 response

I'm closing this as I haven't received a response from you. Please reopen if your problem persists once this commit is available in a release.
