### ISSUE TITLE
Exception with webstorm 2023.2.3 while loading the plugin 2.0.0

### ISSUE THREAD

**Issue by drnushooz** [WarningImHack3r/npm-update-dependencies#41]
### What is the issue?

The plugin fails to load with the following stack trace in a .ts file. Stack trace below. This is on a Mac.
```
   
   com.intellij.diagnostic.PluginException: annotator: com.github.warningimhack3r.npmupdatedependencies.ui.annotation.UpdatesAnnotator@14e7a013 (class com.github.warningimhack3r.npmupdatedependencies.ui.annotation.UpdatesAnnotator) [Plugin: com.github.warningimhack3r.npmupdatedependencies]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.processError(ExternalToolPass.java:251)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:210)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:201)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$0(ExternalToolPass.java:164)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:266)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$2(ExternalToolPass.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:360)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:162)
	at com.intellij.util.ui.update.Update.runUpdate(Update.java:114)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:348)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:338)
	at com.intellij.util.ui.update.MergingUpdateQueue.doFlush(MergingUpdateQueue.java:295)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:254)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:373)
	at com.intellij.util.Alarm$Request.run(Alarm.java:360)
	at com.intellij.util.concurrency.Propagation.contextAwareCallable$lambda$2(propagation.kt:328)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "String.trim()" because "value" is null
	at com.vdurmont.semver4j.Semver.<init>(Semver.java:26)
	at com.vdurmont.semver4j.Requirement.hyphenRequirement(Requirement.java:487)
	at com.vdurmont.semver4j.Requirement.evaluateReversePolishNotation(Requirement.java:338)
	at com.vdurmont.semver4j.Requirement.buildWithTokenizer(Requirement.java:138)
	at com.vdurmont.semver4j.Requirement.buildNPM(Requirement.java:112)
	at com.vdurmont.semver4j.Semver.satisfies(Semver.java:167)
	at com.github.warningimhack3r.npmupdatedependencies.backend.engine.PackageUpdateChecker.hasUpdateAvailable(PackageUpdateChecker.kt:55)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.UpdatesAnnotator$doAnnotate$2.invokeSuspend(UpdatesAnnotator.kt:39)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.UpdatesAnnotator$doAnnotate$2.invoke(UpdatesAnnotator.kt)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.UpdatesAnnotator$doAnnotate$2.invoke(UpdatesAnnotator.kt)
	at com.github.warningimhack3r.npmupdatedependencies.backend.extensions.ExtensionsKt$parallelMap$1$1$1$1.invokeSuspend(Extensions.kt:10)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

### What are the steps to reproduce this issue?

Install webstorm, have a ts file and load with outdated plugins in package.json.

### What were you expecting to happen?

The plugin loading without any issues.

### What OS are you experiencing the problem on?

macOS

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
Thanks for letting me know! I will take a look at this ASAP

**Comment by WarningImHack3r** [comment]
@drnushooz can you send me your `package.json` please? At least your `dependencies` & `devDependencies`

**Comment by WarningImHack3r** [comment]
Just pushed a modification that might fix your problem. I can't reproduce your issue locally so I'll check your file against the new code and push an update right away if everything works fine.

**Comment by drnushooz** [comment]
Here are the dependencies 
```
"dependencies": {
    "aws-sdk": "^2.1475.0",
    "cors": "^2.8.5",
    "dotenv": "^16.3.1",
    "express": "^4.18.2",
    "express-basic-auth": "^1.2.1",
    "http-proxy-middleware": "^2.0.6",
    "morgan": "^1.10.0",
    "node-fetch": "^2.7.0",
    "react-idle-timer": "^5.7.2",
    "reselect": "^4.1.8",
    "socks-proxy-agent": "^8.0.2",
    "source-map-explorer": "^2.5.3",
    "winston": "^3.11.0"
  }
```

And dev deps
```
"devDependencies": {
    "@babel/core": "^7.23.2",
    "@babel/eslint-parser": "^7.22.15",
    "@commitlint/cli": "^17.8.0",
    "@date-io/core": "^2.17.0",
    "@date-io/date-fns": "^2.17.0",
    "@material-ui/core": "^4.12.3",
    "@material-ui/icons": "^4.11.3",
    "@material-ui/lab": "^4.0.0-alpha.60",
    "@material-ui/pickers": "^3.3.11",
    "@mindblowing/commitlint-config-jira": "^1.7.0",
    "@mindblowing/commitlint-plugin-jira-rules": "^1.7.0",
    "@redux-devtools/extension": "^3.2.5",
    "@semantic-release/changelog": "^6.0.3",
    "@semantic-release/commit-analyzer": "^9.0.2",
    "@semantic-release/git": "^10.0.1",
    "@semantic-release/gitlab": "^9.5.1",
    "@semantic-release/release-notes-generator": "^10.0.3",
    "@sentry/browser": "^7.74.1",
    "@sentry/integrations": "^7.74.1",
    "@sentry/react": "^7.74.1",
    "@sentry/tracing": "^7.74.1",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^11.2.7",
    "@testing-library/react-hooks": "^8.0.1",
    "@testing-library/user-event": "^14.5.1",
    "@types/express": "^4.17.20",
    "@types/jest": "^26.0.24",
    "@types/js-cookie": "^3.0.5",
    "@types/node": "^12.20.55",
    "@types/react": "^17.0.69",
    "@types/react-dom": "^17.0.21",
    "@types/react-router-dom": "^5.3.3",
    "@types/react-slick": "^0.23.11",
    "@types/uuid": "^8.3.4",
    "@typescript-eslint/eslint-plugin": "^5.62.0",
    "@typescript-eslint/parser": "^5.62.0",
    "babel-loader": "^8.3.0",
    "canvas-size": "^1.2.6",
    "clsx": "^1.2.1",
    "date-fns": "^2.30.0",
    "eslint": "^8.51.0",
    "eslint-config-prettier": "^8.10.0",
    "eslint-import-resolver-typescript": "^3.6.1",
    "eslint-plugin-import": "^2.28.1",
    "eslint-plugin-jest": "^26.9.0",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-testing-library": "^5.11.1",
    "formik": "^2.4.5",
    "husky": "^8.0.3",
    "jest-junit": "^13.2.0",
    "jest-openapi": "^0.14.2",
    "js-cookie": "^3.0.5",
    "js-yaml": "^4.1.0",
    "konva": "^9.2.2",
    "mnemonist": "^0.39.5",
    "openapi-runtime-validator": "^1.2.1",
    "prettier": "^2.8.8",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-konva": "^17.0.2-0",
    "react-query": "^3.39.3",
    "react-redux": "^7.2.9",
    "react-router-dom": "^5.3.4",
    "react-scripts": "^5.0.1",
    "react-use-dimensions": "^1.2.1",
    "redux": "^4.2.1",
    "redux-saga": "^1.2.3",
    "semantic-release": "^19.0.5",
    "swagger-typescript-api": "^13.0.3",
    "typeof": "^1.0.0",
    "typescript": "^4.9.5",
    "uuid": "^9.0.1",
    "web-vitals": "^3.5.0",
    "yup": "^1.3.2"
  }
```

**Comment by drnushooz** [comment]
> Just pushed a modification that might fix your problem. I can't reproduce your issue locally so I'll check your file against the new code and push an update right away if everything works fine.

Sounds good. I can test the build and inform you. Happy to help with testing.

**Comment by WarningImHack3r** [comment]
@drnushooz I can indeed confirm that the issue is fixed! I managed to reproduce your bug with your dependencies, and it doesn't happen anymore with the latest commits :)

This new version will also improve the algorithm to detect the replacement packages for deprecated dependencies & fix icons not appearing on the menus since the New UI!

**Comment by drnushooz** [comment]
Thank you for fixing this so quickly. Is there a release planned with this fix?

**Comment by WarningImHack3r** [comment]
Yes as I said I will release this alongside the changes I mentioned. I'm just waiting for an answer from the JetBrains team to figure out why I can't make the icon work on the New UI.  
As soon as it's fixed I release the new version :)

**Comment by WarningImHack3r** [comment]
Just been accepted! Enjoy the fix :)
Thanks again for your report!
