### ISSUE TITLE
Error plugin

### ISSUE THREAD

**Issue by CrazyBoy49z** [WarningImHack3r/npm-update-dependencies#5]
```
ExternalToolPass: 

com.intellij.diagnostic.PluginException: annotator: com.github.warningimhack3r.npmupdatedependencies.ui.annotation.UpdatesAnnotator@6f05b774 (class com.github.warningimhack3r.npmupdatedependencies.ui.annotation.UpdatesAnnotator) [Plugin: com.github.warningimhack3r.npmupdatedependencies]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.processError(ExternalToolPass.java:263)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:203)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:278)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$1(ExternalToolPass.java:181)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:366)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:344)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:180)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:334)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:324)
	at com.intellij.util.ui.update.MergingUpdateQueue.doExecute(MergingUpdateQueue.java:281)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:264)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:238)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:241)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:377)
	at com.intellij.util.Alarm$Request.run(Alarm.java:366)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:205)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException
	at com.github.warningimhack3r.npmupdatedependencies.backend.PackageUpdateChecker.hasUpdateAvailable(PackageUpdateChecker.kt:51)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.UpdatesAnnotator$doAnnotate$1.invokeSuspend(UpdatesAnnotator.kt:27)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.UpdatesAnnotator$doAnnotate$1.invoke(UpdatesAnnotator.kt)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.UpdatesAnnotator$doAnnotate$1.invoke(UpdatesAnnotator.kt)
	at com.github.warningimhack3r.npmupdatedependencies.backend.ExtensionsKt$parallelMap$1$1$1$1.invokeSuspend(Extensions.kt:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
PhpStorm 2022.3.3
Build #PS-223.8836.42, built on March 10, 2023
Licensed to Yurij Finiv
Subscription is active until September 17, 2023.
Runtime version: 17.0.6+1-b653.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.3
GC: G1 Young Generation, G1 Old Generation
Memory: 4048M
Cores: 8
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.windowSystem.autoShowProcessPopup=true
    run.processes.with.pty=TRUE
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.github.czy211.licensetemplate (2.0.0)
    LiveTemplatePreview (0.3)
    ideanginx9 (0.1.9)
    color.scheme.Darcula Red (0.3)
    com.intellij.javafx (1.0.4)
    varme.pw.oceanic-dark-theme (1.1.5)
    com.guohanlin.JsonToAnyLanguage (1.1.0)
    lermitage.intellij.extratci (1.24.0)
    com.unger1984.npmdependencychecker (0.0.3)
    MultiHighlight (3.0.0)
    cc.moky.intellij.plugin.svga-support (1.0.9)
    io.aesy.regex101 (0.2)
    cat.dcat.jbplug.mactabbing (1.1.0)
    com.github.warningimhack3r.npmupdatedependencies (1.1.1)
    me.x150.intellij-code-screenshots (1.3)
    com.github.copilot (1.2.4.2465-nightly)
    com.materkey.codepoints (1.0.2)
    com.mroche.JsonHelper (1.2.0)
    lermitage.intellij.iconviewer (1.20.0)
    com.intellij.properties (223.7571.117)
    lermitage.intellij.worldclock (1.6.0)
    com.wix.sasslint (1.1.2)
    bundled-phpstorm-help (223.8836.42)
    String Manipulation (9.7.1)
    krasa.CpuUsageIndicator (1.14)
    Key Promoter X (2023.1.0)
    com.xtu.plugins.reviewer (1.0.9)
    ee.carlrobert.chatgpt (1.6.2)
    com.wakatime.intellij.plugin (14.1.4)
    com.xiaobing1024.laravel (1.1.1)
    ski.chrzanow.foldableprojectview (1.1.4)
    com.chriscarini.jetbrains.jetbrains-auto-power-saver (2.8.3)
    io.snyk.snyk-intellij-plugin (2.4.54)
    com.github.inxilpro.intellijalpine (v0.4.2)
    lermitage.intellij.battery.status (1.25)
    com.mallowigi (85.1.0)
    zielu.gittoolbox (500.0.5+213)
    mobi.hsz.idea.gitignore (4.4.4)
    izhangzhihao.rainbow.brackets (2023.2.6)
    com.alicannklc.laravel.snippets (1.1.1)
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    com.funivan.idea.phpClean (2022.08.30)
    cn.yiiguxing.plugin.translate (3.4.2)
    ru.adelf.idea.dotenv (2022.3)
    com.mallowigi.colorHighlighter (14.0.0)
    de.espend.idea.php.annotation (9.0.0)
    fr.adrienbrault.idea.symfony2plugin (2022.1.243)
    com.github.dinbtechit.vscodetheme (1.7.7)
    net.rentalhost.plugins.php.hammer (0.21.0)
    dev.nybroe.collector (0.4.0)
    org.i18nally.jetbrainsideplugin (1.4.1.5)
    com.laravel_idea.plugin (7.0.0.223)
    com.pestphp.pest-intellij (1.9.2)
    com.intellij.microservices.ui (223.8214.6)

**Comment by WarningImHack3r** [comment]
Pushed 1.1.2 a few hours ago, sorry for the issue!
