### ISSUE TITLE
[crash] ErrorThrowingAction not implementing ActionUpdateThread

### ISSUE THREAD

**Issue by Spurlos** [WarningImHack3r/npm-update-dependencies#88]
### What is the issue?

Deprecated call use

### What are the steps to reproduce this issue?

Have no idea, just poped up while working on a PHP project with plugin enabled.

### What were you expecting to happen?

No errors.

### Paste any relevant logs, error output, etc.

```shell
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.warningimhack3r.npmupdatedependencies.errorsubmitter.ErrorThrowingAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.warningimhack3r.npmupdatedependencies]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```
```


### What OS are you experiencing the problem on?

Linux

### Additional platform information

Build version: PhpStorm 2024.1 Build: #PS-241.14494.237 March 27, 2024
JRE: 17.0.10+8-b1207.12, JetBrains s.r.o.
JVM: 17.0.10+8-b1207.12, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Linux 6.5.0-27-generic (amd64)

=== Plugins ===
Custom plugins: [Vue Component Creator (2.7.3), JB SDK Bintray Downloader (2.2), Auto Dark Mode (1.8.3-2024.1), Extra Icons Free (2023.4.2), Diff / Patch File Support (2.1.13), Nyan Progress Bar (1.15), Toml (241.14494.150), Shifter (1.9.6), React snippets (1.1.1), NPM Update Dependencies (2.1.4), Tailwind Formatter (2.0.10), Stylus (241.14494.140), Ideolog (222.3.2.0), String Manipulation (9.12.0), Lines Sorter (1.0.1), Tabnine: AI Code Completion & Chat in Java JS/TS Python & More (1.73.0), WakaTime (14.3.13), Regexp Tester (2.2.0), Grazie Pro (0.3.296), GitHub Actions Manager (1.19.0), JetBrains AI Assistant (241.14494.240), Spy-js (241.14494.140), EJS (241.14494.140), IntelliVue (1.2.0), Find Pull Request (2.0.4), SonarLint (10.4.2.78113), Jira Integration (4.8.0), Git Worktree (1.0.1+231), Git Config Commit Template (1.2.0), Git Branch Cleaner (1.1.4), .ignore (4.5.3), Live Edit (241.14494.140), Rainbow Brackets (2024.2.2-241), Php Inspections (EA Extended) (5.0.0.0), .env files support (2024.1), PHP RegExp Support (0.9.7), PHP Toolbox (6.2.0), PHP Annotations (10.0.0), Symfony Support (2023.1.268), Drupal Symfony Bridge (0.6.0), PHP Hammer (0.30.0), GitToolBox (500.2.3+233)]
Disabled plugins:[Key Promoter X (2023.3.0), WordPress (241.14494.237), React Buddy (241.14494.140), Git Scope (2023.1.5), Music Time (2.1.10), Vue Router AutoCompletion (0.4.8), Import Cost (1.4.241), Zalando OpenAPI Editor (1.3.0), Subversion (241.14494.237), GitHub Actions (1.1.11), CircleCI Integration (0.0.15.165), Perforce Helix Core (241.14494.237), SensioLabsInsight (1.2), i18n support (2.6.2), deep-assoc-completion (2022.08.03.001), Elasticsearch (2024.1.2-241), CSV Editor (3.3.0-241), Mercurial (241.14494.237), Context Buddy (0.24), Cypress Support Pro (3.6.3), Blade (241.14494.237), Joomla! (241.14494.237), myBitbucket (0.4), Extra Icons (2024.3.2), i18n Ally (1.4.2.1), Senya Editor (1.2.1), Nx Console (1.19.0), Code Time (2.8.33), Cypress Support (1.6.2)]

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
Whoops! I fixed this in #80 but forgot to port that to that class too...  
Sorry about that, fixing it right now. I'll push 2.1.5 right after, it should be available within 2 days approximately
